### ISSUE TITLE
Implementation of Repos List

### ISSUE THREAD

**Issue by dziermanfelix** [bcdasilv/code-style-mining#13]
File name to list the repos that have been analyzed, ran into an error, or are pending analysis.
Adding this filename to the .properties file.

**Comment by dziermanfelix** [comment]
To speed up the process of running through repos, there should be a repos list to pull from. 
For now, this list can be in your root directory for the project. You can link it to your code with the .properties file (See the README)

Excerpt from the README:
The :owner/:repo that is used in a GET through the GitHub API.
repoURLsPath = "<repo urls path>"

You can make a list of these repo urls a file (let's call it urls.txt) and put the local path to that file in the .properties file. For example, this should go in the .properties file:

repoURLsPath="urls.txt"

The code will iterate through each url in this file.

**Comment by bcdasilv** [comment]
That's similar to what we do in the python analysis. Thanks!
