### ISSUE TITLE
Re-run python analysis after bug fixes

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/code-style-mining#22]
@kramsey458, I'm ready to re-run the analysis on python repos after the bugs you fixed.
Yesterday, I built a new list of repos. I got about 2500 repos using the GH search api using a list of 100 random keywords in order to get repos from diverse domains. Also, I have a list of the top 500 python repos based on number of stars. In that way, we have diverse project domains as well as the most popular ones.

I'm planning to re-run today. Fingers crossed for no major bugs in this iteration.

**Comment by kramsey458** [comment]
@bcdasilv I have a fix ready for issue #21 , where the summary is moved to the outer level. I spoke with Tony in class today and he also had suggestions to bring the JSON objects "classes" and "functions" under "naming analysis" up one level. This way he can avoid nested JSON structures which makes things easier for his development - this should be a quick fix. Should I push these changes now before the python repo analysis is re-run?

**Comment by bcdasilv** [comment]
Ok. Go ahead and push it.

**Comment by kramsey458** [comment]
@bcdasilv Pull request for #21 opened

**Comment by bcdasilv** [comment]
Thanks. I ran yesterday the python analysis using the top 500 repos list. I could get 67 repos analyzed and 17 skipped due to SyntaxError or UnicodeDecodeError while parsing the AST for the naming style analysis. This is a known issue (#2 )
