### ISSUE TITLE
Java JSON Structure

### ISSUE THREAD

**Issue by kramsey458** [bcdasilv/code-style-mining#26]
Currently the JSON structure summary for java analysis looks like this:

{
  "methodsNamingGoogle": 213,
  "methodsCurlyBracesSingleAllman": 0,
  "methodsNamingLowerSnake": 0,
  "methodsIndentsMinIndent": 60,
  "methodsCurlyBracesMultipleExKr": 1,
  "fieldsNamingOther": 55,
  "namingGoogle": 50,
  "methodsCurlyBracesMultipleAllman": 0,
  "methodsNamingOther": 0,
  "fieldsNamingGoogle": 3,
  "methodsCurlyBracesMultipleGoogle": 47,
  "totalFiles": 114,
  "methodsIndentsMaxIndent": 88,
  "repoUrl": "kramsey458/StreakerGame/branches/master",
  "linesOfCodes": 2899,
  "methodsIndentsTabs": 1334,
  "methodsVariableLowerSnake": 0,
  "methodsIndentsSpaces": 1341,
  "methodsVariableOther": 0,
  "fieldsNamingLowerSnake": 0,
  "methodsCurlyBracesSingleOther": 0,
  "methodsVariablesGoogle": 0,
  "methodsLineLength": 24,
  "methodsCurlyBracesMultipleOther": 0,
  "constantsNamingOther": 46,
  "methodsCurlyBracesSingleGoogle": 23,
  "methodsIndentsAvgIndent": 23,
  "constantsNamingGoogle": 0,
  "methodsCurlyBracesSingleExKr": 0,
  "namingOther": 0
}

This is a summation of the file analysis results of every file in the repo.

Analysis for single files in the repo follows this format:

{
  "repoURL": "kramsey458/StreakerGame/branches/master",
  "package": false,
  "filename": "src/logic/client/Client.java",
  "import": true,
  "class": {
    "blank_lines": false,
    "methods": {
      "variables": {
        "naming": {
          "other": 0,
          "lower_snake_case": 0,
          "google": 0
        }
      },
      "indents": {
        "tabs": 14,
        "spaces": 0,
        "min_indent": 2147483647,
        "avg_indent": -1,
        "max_indent": -2147483648
      },
      "line_length": [
        0,
        0
      ],
      "naming": {
        "other": 0,
        "lower_snake_case": 0,
        "google": 2
      },
      "curly_braces": {
        "single": {
          "other": 0,
          "allman": 0,
          "ex_kr": 0,
          "google": 0
        },
        "multiple": {
          "other": 0,
          "allman": 0,
          "ex_kr": 0,
          "google": 0
        }
      }
    },
    "naming": {
      "other": 0,
      "google": 1
    },
    "constants": {
      "naming": {
        "other": 0,
        "google": 0
      }
    },
    "fields": {
      "naming": {
        "other": 0,
        "lower_snake_case": 0,
        "google": 0
      }
    }
  }
}

**Comment by kramsey458** [comment]
Closing this issue as structure has been implemented. Will update wiki with Java JSON structure

**Comment by BryceV** [comment]
Updated wiki
