### ISSUE TITLE
Some json output files for the python analysis include analyzed files from other projects

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/code-style-mining#4]
In the database, some projects have multiple files from other projects under the 'repo_analysis' json object. For example, if you look at this entry 'python-analysis-v02.1991viet/QuickDraw' you're going to see within the repo_analysis json object several files/entries from other projects included there. 
This happens with some other projects.

One possible thing to check, when I talked to @kelliebanzon: Many of the access variables used to track the current repo name, owner, etc. are global. Perhaps the compiler has optimized and run the code in an unexpected order. If the analyzer runs multiple repos concurrently, the global access variables could be inaccurate. We're not sure if that causes the issue though.

**Comment by kramsey458** [comment]
As of 4/15/19, the repository ```1991viet/QuickDraw``` has been removed from Github so I am unable to replicate the issue with this exact repository. However, the repository ```adobe-fonts/source-code-pro``` displays similar symptoms to ```1991viet/QuickDraw``` repository. I have attached images verifying that the issue has been fixed.

Issue #4, ```adobe-fonts/source-code-pro```, before fix:
<img width="624" alt="#4_PREFIX" src="https://user-images.githubusercontent.com/26666766/56182074-368e4400-5fc5-11e9-88fe-c846621490a5.png">

Issue #4, ```adobe-fonts/source-code-pro```, after fix (only the correct repo is included):
<img width="657" alt="#4_POSTFIX" src="https://user-images.githubusercontent.com/26666766/56182087-44dc6000-5fc5-11e9-9a51-687661c4dd21.png">

**Comment by kramsey458** [comment]
This issue falls into the same category as #17 - which has already been fixed. I have verified that this issue cannot occur again with the changes I have pushed. We can close this issue now as it has been resolved.
