### ISSUE TITLE
Jsonify Java analysis

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/code-style-mining#5]
Implement json output files. That was started by @janani-sridhar but still pending. She had implemented some jsonify methods but they were not integrated into the analysis pipeline. Check also the proposed json output for the java analysis on the wiki (this most likely need to be reviewed).

**Comment by dziermanfelix** [comment]
For each repo, each Java file is being JSONified according to the java analysis wiki.
They should be stored locally in a JSON array, though the code has not been finished on that part. 
Next, a summary should be run on this JSON array for the whole repo (once the whole repo has been analyzed). This has not been finished either.

**Comment by kramsey458** [comment]
Added the repo url and the corresponding file paths for class results being added to the JSONify summary class (one summary object per repo url). 
There was also a bug with the JSONify summary being a single object/collection for multiple repository traversals. Moved the JSONify summary class so there is one object created per repo url traversal so there is a way to actually create and summarize the results for each file analyzed.

**Comment by kramsey458** [comment]
The Java analysis is being written to a JSON object and is able to be written to the MongoDB. However, more work needs to be done on how to best structure the internal JSON objects. 
See #26
