### ISSUE TITLE
Implement data persistence for the java analysis

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/code-style-mining#6]
Once the java analysis generates json files as output for the code style analysis, those files need to be stored in our nosql database (currently mongodb).
Each analyzed project should be a json document stored in a mongodb collection. Don't use a unique collection for each project. We're using mongo free tier and there's a limit of 500 collections but one collection supports several documents (perhaps unlimited).

**Comment by kramsey458** [comment]
Implemented MongoDB connection for Java with tests to verify it is correctly connecting. Still need to determine the best way to store the java analysis results - either by adding the analysis for each file in the repo tree (i.e analysis for file1.java, file2.java), or by adding a single analysis that summarizes the errors found collectively in the entire repo.

**Comment by kramsey458** [comment]
Results being persistently saved into MongoDB
