### ISSUE TITLE
Compute and store the file size in terms of LOC

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/code-style-mining#7]
For every file analyzed, compute the number of lines of code (LOC), add the result in the JSON output file to be then stored in the database.

**Comment by kramsey458** [comment]
Implemented way to calculate total lines of code for the Java analysis portion. Still need to investigate Python analysis and counting LOC.

**Comment by BryceV** [comment]
Built a module for this: https://github.com/BryceV/python_loc_counter/tree/v0.1

**Comment by BryceV** [comment]
Added #42 for better Java LOC. Also updated wiki for LOC related features
